%% plotFL - script to plot FL as in G-B thesis

FL = importdata( 'FL.txt' );
%FL(:,2:end)=FL(:,2:end).*pi/2; % arbitrary scale factor
plotopt = { '-r', '-b', '-k', '-c', '-y', '-g' };
figure( 'Name', 'FL', 'NumberTitle', 'Off' );
semilogx( FL(:,1),FL(:,2), ...
          FL(:,1),FL(:,3), ...
          FL(:,1),FL(:,4), ...
          FL(:,1),FL(:,5), ...
          FL(:,1),FL(:,6), ...
          FL(:,1),FL(:,7) );
grid on;axis( [1e-4 1e-1 -.5 1.5 ] );
xlabel( 'x' ); ylabel( 'FL' );
legend( 'Q²=24', 'Q²=32', 'Q²=45', 'Q²=60', 'Q²=80', 'Q²=110' );
